export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_STARTED = 'SIGNUP_STARTED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const GET_FOLLOWERS_NUMBER = 'GET_FOLLOWERS_NUMBER ';
export const GET_FOLLOWING_NUMBER = 'GET_FOLLOWING_NUMBER ';
export const GET_FOLLOWING = 'GET_FOLLOWING ';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ARTICLES = 'GET_ARTICLES';

export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
export const REPORT_ARTICLES = 'REPORT_ARTICLES';
