export const CLEAR_LIKES_DISLIKES = 'CLEAR_LIKES_DISLIKES';
export const LIKE_ARTICLE = 'LIKE_ARTICLE';
export const DISLIKE_ARTICLE = 'DISLIKE_ARTICLE';
export const GET_LIKES_ARTICLE = 'GET_LIKES_ARTICLE';
export const GET_DISLIKES_ARTICLE = 'GET_DISLIKES_ARTICLE';
